version: '3.7'

services:
  http-simple:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "${HTTP_PORT}:80"
  nginx:
    image: nginx
    volumes:
      - ".:/etc/nginx/conf.d"
    ports:
      - "${HTTPS_PORT}:443"